/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "std_types.h"
#include "arm_util.h"

#include "RCC.h"
#include "GPIO.h"
#include "EXTI.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint32_t IRQ_Flag = 0;
EXTI_PinConfig_t EXTI_Config;
GPIO_PinConfig_t PinConfig;

void EXTI0_CallBack(){
	IRQ_Flag = 1;
}

void clock_init(){
	RCC_init();
	RCC_enableClock(RCC_APB2, RCC_APB2ENR_IOPAEN);
	RCC_enableClock(RCC_APB2, RCC_APB2ENR_IOPBEN);
}

void LED_init(){

	PinConfig.GPIO_PinNumber = GPIO_PIN_2;
	PinConfig.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinConfig.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_2M;

	GPIO_init(GPIOA, &PinConfig);
}

void Interrupt_init(){

	EXTI_Config.EXTI_PIN = EXTI0PB0;
	EXTI_Config.Trigger = EXTI_Trigger_RisingAndFalling;
	EXTI_Config.IRQ_EN = EXTI_IRQ_Enable;
	EXTI_Config.P_IRQ_CallBack = EXTI0_CallBack;

	MCAL_EXTI_init(&EXTI_Config);
}

int main(void)
{

	clock_init();
	LED_init();
	Interrupt_init();

	//IRQ_Flag = 1;

	while(1){
		if(IRQ_Flag){
			GPIO_TogglePin(GPIOA, GPIO_PIN_2);
			//delay_ms(1000);
			IRQ_Flag = 0;
		}
	}
}
